=== JunkWaxData/CardLists/schemas/release.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "nonEmptyString": {
      "type": "string",
      "pattern": "^\\S(.*\\S)?$"
    },
    "versionString": {
      "type": "string",
      "pattern": "^[0-9]+\\.[0-9]+$"
    },
    "uuid": {
      "type": "string",
      "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
    },
    "oddsString": {
      "type": "string",
      "pattern": "^[0-9]+:[0-9,]+$"
    },
    "productOdds": {
      "type": "object",
      "properties": {
        "product": { "type": "string" },
        "odds": { "$ref": "#/definitions/oddsString" }
      },
      "required": [
        "product",
        "odds"
      ],
      "additionalProperties": false
    },
    "attributeNotePair": {
      "type": "object",
      "properties": {
        "attribute": { "$ref": "#/definitions/nonEmptyString" },
        "note": { "$ref": "#/definitions/nonEmptyString" }
      },
      "required": [
        "attribute",
        "note"
      ],
      "additionalProperties": false
    },
    "variation": {
      "type": "object",
      "properties": {
        "variation": { "$ref": "#/definitions/nonEmptyString" },
        "note": { "$ref": "#/definitions/nonEmptyString" },
        "insertOdds": {
          "type": "array",
          "items": { "$ref": "#/definitions/productOdds" }
        },
        "parallels": {
          "type": "array",
          "items": { "$ref": "#/definitions/parallel" }
        },
        "attributes": {
          "type": "array",
          "items": { "$ref": "#/definitions/nonEmptyString" }
        },
        "numberedTo": {
          "type": "integer",
          "minimum": 1
        }
      },
      "required": [
        "variation"
      ],
      "additionalProperties": false
    },
    "parallel": {
      "type": "object",
      "properties": {
        "name": { "$ref": "#/definitions/nonEmptyString" },
        "numberedTo": {
          "type": "integer",
          "minimum": 1
        },
        "notes": {
          "type": "array",
          "items": { "$ref": "#/definitions/nonEmptyString" }
        },
        "insertOdds": {
          "type": "array",
          "items": { "$ref": "#/definitions/productOdds" }
        }
      },
      "required": [
        "name"
      ],
      "additionalProperties": false
    },
    "card": {
      "type": "object",
      "properties": {
        "uniqueId": { "$ref": "#/definitions/uuid" },
        "number": {
          "type": "string",
          "pattern": "^[a-zA-Z0-9 .-]*$"
        },
        "name": { "$ref": "#/definitions/nonEmptyString" },
        "attributes": {
          "type": "array",
          "items": { "$ref": "#/definitions/nonEmptyString" }
        },
        "insertOdds": {
          "type": "array",
          "items": { "$ref": "#/definitions/productOdds" }
        },
        "note": { "$ref": "#/definitions/nonEmptyString" },
        "variations": {
          "type": "array",
          "items": { "$ref": "#/definitions/variation" }
        },
        "parallels": {
          "type": "array",
          "items": { "$ref": "#/definitions/parallel" }
        },
        "numberedTo": {
          "type": "integer",
          "minimum": 1
        }
      },
      "required": [
        "uniqueId",
        "name"
      ],
      "additionalProperties": false
    },
    "set": {
      "type": "object",
      "properties": {
        "uniqueId": { "$ref": "#/definitions/uuid" },
        "name": { "$ref": "#/definitions/nonEmptyString" },
        "notes": {
          "type": "array",
          "items": { "$ref": "#/definitions/nonEmptyString" }
        },
        "numberedTo": {
          "type": "integer",
          "minimum": 1
        },
        "insertOdds": {
          "type": "array",
          "items": { "$ref": "#/definitions/productOdds" }
        },
        "variations": {
          "type": "array",
          "items": { "$ref": "#/definitions/variation" }
        },
        "parallels": {
          "type": "array",
          "items": { "$ref": "#/definitions/parallel" }
        },
        "attributes": {
          "type": "array",
          "items": { "$ref": "#/definitions/nonEmptyString" }
        },
        "cards": {
          "type": "array",
          "items": { "$ref": "#/definitions/card" }
        }
      },
      "required": [
        "uniqueId",
        "name",
        "cards"
      ],
      "additionalProperties": false
    }
  },
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string",
      "format": "uri"
    },
    "name": { "$ref": "#/definitions/nonEmptyString" },
    "version": { "$ref": "#/definitions/versionString" },
    "uniqueId": { "$ref": "#/definitions/uuid" },
    "attributes": {
      "type": "array",
      "items": { "$ref": "#/definitions/attributeNotePair" }
    },
    "notes": {
      "type": "array",
      "items": { "$ref": "#/definitions/nonEmptyString" }
    },
    "sets": {
      "type": "array",
      "items": { "$ref": "#/definitions/set" }
    }
  },
  "required": [
    "$schema",
    "name",
    "version",
    "uniqueId",
    "sets"
  ],
  "additionalProperties": false
}

=== JunkWaxData/CardLists/categories/baseball/1994/1994-Upper-Deck.json
{
    "$schema": "https://raw.githubusercontent.com/JunkWaxData/CardLists/refs/heads/main/schemas/release.json",
    "name": "1994 Upper Deck Baseball",
    "version": "1.1",
    "uniqueId": "2d9a1fcb-f8db-4c65-906f-5171936f60bf",
    "attributes": [
        {
            "attribute": "SR",
            "note": "Star Rookie"
        },
        {
            "attribute": "RC",
            "note": "Rookie Card"
        },
        {
            "attribute": "UER",
            "note": "Uncorrected Error"
        },
        {
            "attribute": "FT",
            "note": "Fantasy Team"
        },
        {
            "attribute": "FUT",
            "note": "Future is Now"
        },
        {
            "attribute": "HFA",
            "note": "Home Field Advantage"
        },
        {
            "attribute": "UDCA",
            "note": "Upper Deck Classic Alumni"
        },
        {
            "attribute": "DD",
            "note": "Diamond Debuts"
        },
        {
            "attribute": "TP",
            "note": "Top Prospect"
        },
        {
            "attribute": "AU",
            "note": "Autograph"
        }
    ],
    "sets": [
        {
            "name": "Series 1",
            "parallels": [
                {
                    "name": "Electric Diamond",
                    "insertOdds": [
                        {
                            "product": "Series 1 Hobby Pack",
                            "odds": "1:1"
                        }
                    ]
                }
            ],
            "cards": [
                {
                    "number": "1",
                    "name": "Brian Anderson",
                    "attributes": [
                        "SR",
                        "RC"
                    ],
                    "uniqueId": "17628e1d-65b9-4c88-88f8-49e139a3a9a7"
                },
                {
                    "number": "2",
                    "name": "Shane Andrews",
                    "attributes": [
                        "SR"
                    ],
                    "uniqueId": "ce3e44ad-3391-4341-8d4b-983040267102"
                },
                {
                    "number": "3",
                    "name": "James Baldwin",
                    "attributes": [
                        "SR"
                    ],
                    "uniqueId": "fd28950a-6c11-4b35-a842-fe0c00bac0c6"
                },
                {
                    "number": "4",
                    "name": "Rich Becker",
                    "attributes": [
                        "SR"
                    ],
                    "uniqueId": "ac270ca3-b906-49b6-9b85-5f45b5e54894"
                },
                {
                    "number": "5",
                    "name": "Greg Blosser",
                    "attributes": [
                        "SR"
                    ],
                    "uniqueId": "fb8294b1-0aa5-4771-88c5-f9dd92e8b982"
                },
                {
                    "number": "6",
                    "name": "Ricky Bottalico",
                    "attributes": [
                        "SR",
                        "RC"
                    ],
                    "uniqueId": "996a5993-5453-482b-8676-295509811b84"
                },
                {
                    "number": "7",
                    "name": "Midre Cummings",
                    "attributes": [
                        "SR"
                    ],
                    "uniqueId": "bef33720-8e65-439c-a32a-c58d058d3975"
                },
                {
                    "number": "8",
                    "name": "Carlos Delgado",
                    "attributes": [
                        "SR"
                    ],
                    "uniqueId": "36a1b64c-e77d-4fc3-82bf-903212a6bbad"
                },
                {
                    "number": "9",
                    "name": "Steve Dreyer",
                    "attributes": [
                        "SR",
                        "RC"
                    ],
                    "uniqueId": "14a8c7d5-a140-4864-9997-4b60e0a2f63e"
                },
                {
                    "number": "10",
                    "name": "Joey Eischen",
                    "attributes": [
                        "SR"
                    ],
                    "uniqueId": "15767aa7-2f09-4f5e-a4a9-f09122699263"
                },
                {
                    "number": "11",
                    "name": "Carl Everett",
                    "attributes": [
                        "SR",
                        "UER"
                    ],
                    "uniqueId": "ce6aaaa1-7a4d-4fb2-820c-22d4b2716c6b"
                },
                {
                    "number": "12",
                    "name": "Cliff Floyd",
                    "attributes": [
                        "SR",
                        "UER"
                    ],
                    "uniqueId": "307b4feb-8d9c-4635-af3c-e696a1819cb3"
                },
                {
                    "number": "13",
                    "name": "Alex Gonzalez",
                    "attributes": [
                        "SR"
                    ],
                    "uniqueId": "cf6bd5a2-5030-4c01-9050-0641b5da5a74"
                },
                {
                    "number": "14",
                    "name": "Jeff Granger",
                    "attributes": [
                        "SR"
                    ],
                    "uniqueId": "9b9506cd-c559-4bdb-bcea-c811df2a83a4"
                },
                {
                    "number": "15",
                    "name": "Shawn Green",
                    "attributes": [
                        "SR"
                    ],
                    "uniqueId": "c0b59904-af0e-4e42-ae3d-5f94e7cdf1f0"
                },
                {
                    "number": "16",
                    "name": "Brian Hunter",
                    "attributes": [
                        "SR"
                    ],
                    "uniqueId": "529a6511-6cd9-4f74-9288-f74e7462551c"
                },
                {
                    "number": "17",
                    "name": "Butch Huskey",
                    "attributes": [
                        "SR"
                    ],
                    "uniqueId": "4c68b390-9c34-43c7-a35d-984ccebb58ee"
                },
                {
                    "number": "18",
                    "name": "Mark Hutton",
                    "attributes": [
                        "SR"
                    ],
                    "uniqueId": "ae269011-4ce1-497a-8b6b-1cdeaff6d9f3"
                },
                {
                    "number": "19",
                    "name": "Michael Jordan",
                    "attributes": [
                        "SR",
                        "RC"
                    ],
                    "uniqueId": "fefc27b4-66d8-4065-9c92-9e5723de529c"
                },
                {
                    "number": "20",
                    "name": "Steve Karsay",
                    "attributes": [
                        "SR"
                    ],
                    "uniqueId": "ce522cae-0967-4cfa-8823-452c73359983"
                },
                {
                    "number": "21",
                    "name": "Jeff McNeely",
                    "attributes": [
                        "SR"
                    ],
                    "uniqueId": "65c5ed97-0620-4962-b7e8-32acd8d3ed82"
                },
                {
                    "number": "22",
                    "name": "Marc Newfield",
                    "attributes": [
                        "SR"
                    ],
                    "uniqueId": "e5ff6f00-eb10-4dcb-bf4b-a432448c9b77"
                },
                {
                    "number": "23",
                    "name": "Manny Ramirez",
                    "attributes": [
                        "SR"
                    ],
                    "uniqueId": "9887f620-ed53-41f3-b150-7bac5ce24a2e"
                },
                {
                    "number": "24",
                    "name": "Alex Rodriguez",
                    "attributes": [
                        "SR",
                        "RC"
                    ],
                    "uniqueId": "f31457f2-2231-451e-8f99-df1c35d7ee82"
                },
                {
                    "number": "25",
                    "name": "Scott Ruffcorn",
                    "attributes": [
                        "SR",
                        "UER"
                    ],
                    "uniqueId": "18cded6a-35bf-41fb-b949-b9784275a60a"
                },
                {
                    "number": "26",
                    "name": "Paul Spoljaric",
                    "attributes": [
                        "SR",
                        "UER"
                    ],
                    "uniqueId": "6bcb1315-3cfc-4f88-8c95-a288aa2c290c"
                },
                {
                    "number": "27",
                    "name": "Salomon Torres",
                    "attributes": [
                        "SR"
                    ],
                    "variations": [
                        {
                            "variation": "Silver background on Back"
                        }
                    ],
                    "uniqueId": "ea57b9b8-cd37-4a24-a17e-4b4c44ba3797"
                },
                {
                    "number": "28",
                    "name": "Steve Trachsel",
                    "attributes": [
                        "SR"
                    ],
                    "uniqueId": "31031c33-9373-4fe1-93be-9c1e690a6f87"
                },
                {
                    "number": "29",
                    "name": "Chris Turner",
                    "attributes": [
                        "SR"
                    ],
